# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Core C++ 2023"
email: "info@corecpp.org"
description: "Core C++ 2023"
baseurl: ""
url: "https://corecpp.org"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-128126696-1"
googleAnalyticsSiteUrl: "corecpp.org"
siteVerification: ""

# Organizer Info
organizerName: "Core C++"
organizerAlternateName: "The Core C++ 2023 Conference"
organizerDescription: "The Core C++ User Group."
organizerEmail: "info@corecpp.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://corecpp.org/"

# Head
metaKeywords: "event, C++, conference, programming, developers, lectures, Israel, speakers"
twitterAccount: "@corecpp"
# socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://cfs.corecpp.org/"
c4sponsorsUrl:  "mailto:corecpp.org" # "/assets/CoreCpp2023_SponsoringOffer.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
# - {link: "https://2019.corecpp.org", text: "Core C++ 2019"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
# - {link: "https://ti.to/hamakor/core-cpp-2023", text: "Register"}
 - {link: "/assets/CoreCpp2023_CallForSpeakers.pdf", text: "Call For Speakers"}
# - {link: "https://cfs.corecpp.org/", text: "Submit Your Talk"}
# - {link: "/assets/CoreCpp2023_CallForTutorials.pdf", text: "Call For Tutorials"}
 #- {link: "/assets/CoreCpp2023_SponsoringOffer.pdf", text: "Sponsor Us"}
rightNavigationButtons:
# - {link: "https://ti.to/hamakor/core-cpp-2023", text: "Register"}
 - {link: "/assets/CoreCpp2023_CallForSpeakers.pdf", text: "Call For Speakers"}
# - {link: "https://cfs.corecpp.org/", text: "Submit Your Talk"}
# - {link: "/assets/CoreCpp2023_CallForTutorials.pdf", text: "Call For Tutorials"}
# - {link: "/assets/CoreCpp2023_SponsoringOffer.pdf", text: "Sponsor Us"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Core C++ <typeout> 2023"
eventDate: "June 5-7, 2023"
typeoutTextValues: '"", "Conference", "Summer", "Israel", "co_return"'
typeoutFallback: "Conference"
heroButtons:
# - {link: "https://ti.to/hamakor/core-cpp-2023", text: "Register"}
 - {link: "/assets/CoreCpp2023_CallForSpeakers.pdf", text: "Call For Speakers"}
# - {link: "https://cfs.corecpp.org/", text: "Submit Your Talk"}
# - {link: "/assets/CoreCpp2023_CallForTutorials.pdf", text: "Call For Tutorialsbeo"}
# - {link: "/assets/CoreCpp2023_SponsoringOffer.pdf", text: "Sponsor Us"}
 
# About Block
aboutTitle: "About Core C++ 2023"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "We are back with the second C++ conference in Israel brought to you by The Core C++ User Group! Awesome speakers and lots of fun!" }
# - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite C++ feature!" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Want some real team and skill building? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "400", specialCharacter: "+", info: "attendees", detail: "face to face"}
 - {count: "30", specialCharacter: "+", info: "hours", detail: "of C++ goodness"}
 - {count: "30", specialCharacter: "+", info: "speakers", detail: "international and local"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "and other activities"}

# Latest News Block
latestNewsTitle: "Latest News"

# Topics Block
topicsTitle: "Topics"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "The Tel-Aviv" 
#eventLocationLink: "https://www.int.mta.ac.il/"
#eventStreetAddress: "Rabenu Yeruham St."
eventAddressLocality: "Tel Aviv"
#eventPostalCode: "6818211"
eventAddressCountry: "Israel"
eventStartTime: "2023-06-05T09:00"
eventDoorTime: "08:00"
eventEndTime: "2023-06-07T18:00"   
eventPlaceCoordinates: "32.072279, 34.788976"
mapCenterCoordinates: "32.072279, 34.788976"
mapMobileCenterCoordinates: "32.072279, 34.788976"

#eventLocationName: "The Tel-Aviv Yaffo Academic College" 
#eventLocationLink: "https://www.int.mta.ac.il/"
#eventStreetAddress: "Rabenu Yeruham St."
#eventAddressLocality: "Tel Aviv"
#eventPostalCode: "6818211"
#eventPlaceCoordinates: "32.0474639, 34.760838631217915"
#mapCenterCoordinates: "32.0474639, 34.760838631217915"
#mapMobileCenterCoordinates: "32.0474639, 34.760838631217915"

# Venue Block
venueBlockTitle: "Core C++ 2022"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
venueTitle: "Tel-Aviv"
#venueFeatures: ["Located in the heart of Tel-Aviv and Jaffa"]

#venueBlockTitle: "Venue"
#venueBigImage: "venue_0.jpg"
#venueSmallImage1: "venue_1.jpg"
#venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
#venueTitle: "Tel-Aviv Yaffo Academic College"
#venueFeatures: ["Located in the heart of Tel-Aviv and Jaffa"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "corecpp2023"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
#subscribeImage: "subscribe.jpg"
#subscribeTitle: "Subscribe for updates"
#subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
#subscribeInfo: "Number of seats is limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Price Table"
ticketsInfo: "0% VAT."
ticketsOffers:
# -
#  name: "Full 2-Day Ticket: Early Bird"
#  price: "850"
#  priceCurrency: "ILS"
#  ribbon: "-20%"
#  featured: true
#  ticketsNumber: "50"
#  buyButtonLink: "https://ti.to/hamakor/core-cpp-2022/with/3cpa-nmkm34"
#  buyButtonText: "Register Now"
#  ticketContentList: ["Two Day Conference", "Three Parallel Tracks", "On Sale Until June 30th!"]
#  validFrom: "2021-06-01"
#  validThrough: "2021-06-30"
#  soldOut: false
#  soldOutText: "Sold Out"
 -
  name: "Full 2-Day Ticket"
  price: "1050"
  priceCurrency: "ILS"
  featured: true
  ticketsNumber: "300"
  buyButtonLink: "https://ti.to/hamakor/core-cpp-2022/with/trbrwbmshfg"
  buyButtonText: "Register Now"
  ticketContentList: ["Two Day Conference", "Three Parallel Tracks", "Meet Fellow Developers"]
  validFrom: "2021-07-01"
  validThrough: "2021-09-05"
  soldOut: true
  soldOutText: "Waiting List"
 -
  name: "Workshop"
  price: "1350"
  priceCurrency: "ILS"
  ribbon: "Limited"
  featured: true
  ticketsNumber: "100"
  buyButtonLink: "https://ti.to/hamakor/core-cpp-2022"
  buyButtonText: "Register Now"
  ticketContentList: ["Full day workshop", "3 workshops to chose from!", "Top C++ trainers"]
  validFrom: "2021-07-01"
  validThrough: "2021-09-05"
  soldOut: false
  soldOutText: "Event Ended"

# Footer
socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=corecpp", icon: "twitter"}
 - {link: "https://facebook.com/corecpp", icon: "facebook"}
 - {link: "https://www.youtube.com/channel/UCE14XYFaK1fDTnOTqlOFrrQ", icon: "youtube"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.meetup.com/CoreCpp", text: "Core C++ User Group"}
   - {link: "https://www.meetup.com/haifa-cpp", text: "Haifa::C++ User Group"}
   - {link: "https://www.int.mta.ac.il/", text: "The Academic College of Tel Aviv-Yaffo"}

 -
  title: "Contacts"
  links:
   - {link: "mailto:info@corecpp.org", text: "info@corecpp.org"}
 -
  title: "Code of Conduct"
  links:
   - {permalink: "https://berlincodeofconduct.org/", text: "Berlin Code of Conduct"}

# Blog
blogTitle: "Latest News"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "The Core C++ conference is a non-for-profit, community-based and community-facing event.
          It is organized by The Core C++ and Haifa::C++ user groups, and by enthusiasts from the local and global C++ community.
          Our goal is to bring high quality content, great speakers and a fantastic community building experience to C++ developers in Israel 
          and to promote software quality using the latest best practices, tools and languages features."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "32.0474639, 34.760838631217915"
logisticsMapMobileCenterCoordinates: "32.0474639, 34.760838631217915"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
